// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDy_AtQeJhkLxpfcy8bdZs45OJegpEP5I',
    appId: '1:1092762606761:web:66af5413a5ac618b329db8',
    messagingSenderId: '1092762606761',
    projectId: 'fruits-hub-43dd9',
    authDomain: 'fruits-hub-43dd9.firebaseapp.com',
    storageBucket: 'fruits-hub-43dd9.appspot.com',
    measurementId: 'G-S1XHTL033W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBJS8sc1HFdCnS9Uv0R2HD7aHqX1KOP20',
    appId: '1:1092762606761:android:d790855ae77afa20329db8',
    messagingSenderId: '1092762606761',
    projectId: 'fruits-hub-43dd9',
    storageBucket: 'fruits-hub-43dd9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPKouB2EBY6j8HiC8szU2ht4Dwk2_n2pA',
    appId: '1:1092762606761:ios:17618b3a274e47cf329db8',
    messagingSenderId: '1092762606761',
    projectId: 'fruits-hub-43dd9',
    storageBucket: 'fruits-hub-43dd9.appspot.com',
    androidClientId: '1092762606761-mmk3d7k84l9g4vbj4799u695ql1mu1om.apps.googleusercontent.com',
    iosClientId: '1092762606761-leubons5abeq6fe8rk5je3ni130imrgq.apps.googleusercontent.com',
    iosBundleId: 'com.example.fruitsHubDashboard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAPKouB2EBY6j8HiC8szU2ht4Dwk2_n2pA',
    appId: '1:1092762606761:ios:17618b3a274e47cf329db8',
    messagingSenderId: '1092762606761',
    projectId: 'fruits-hub-43dd9',
    storageBucket: 'fruits-hub-43dd9.appspot.com',
    androidClientId: '1092762606761-mmk3d7k84l9g4vbj4799u695ql1mu1om.apps.googleusercontent.com',
    iosClientId: '1092762606761-leubons5abeq6fe8rk5je3ni130imrgq.apps.googleusercontent.com',
    iosBundleId: 'com.example.fruitsHubDashboard',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCDy_AtQeJhkLxpfcy8bdZs45OJegpEP5I',
    appId: '1:1092762606761:web:d0adf3a0760b7e80329db8',
    messagingSenderId: '1092762606761',
    projectId: 'fruits-hub-43dd9',
    authDomain: 'fruits-hub-43dd9.firebaseapp.com',
    storageBucket: 'fruits-hub-43dd9.appspot.com',
    measurementId: 'G-NJRZYCY19H',
  );
}
